spring:
  redis:
    database: 0
    host: 192.168.1.17
    port: 6379
#    password:
    cluster:
      nodes:
      - 192.168.1.17:6379
#      - 127.0.0.1:6380
#      - 127.0.0.1:6381
#      - 127.0.0.1:6382
#    jedis:
    lettuce:
      pool:
         # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000